# WRF-CMake (https://github.com/WRF-CMake/WRF).
# Copyright 2019 M. Riechert and D. Meyer. Licensed under the MIT License.

# Runs on commits to the wrf-cmake branch and PRs.
trigger:
- wrf-cmake

# Run every week even if there are no code changes.
# Catches any problems due to new dependency versions from package managers.
schedules:
- cron: "0 0 * * Wed"
  displayName: Weekly build
  branches:
    include: [ wrf-cmake ]
  always: true

jobs:
- template: .ci/azure-pipelines/matrix.yml
  parameters:
    WATS_DIFF: false
    WATS_PLOTS: true
