# WRF-CMake (https://github.com/WRF-CMake/wrf).
# Copyright 2019 M. Riechert and D. Meyer. Licensed under the MIT License.

jobs:
- job: ${{ parameters.OS_NAME }}_${{ parameters.BUILD_SYSTEM }}_${{ parameters.BUILD_TYPE }}_${{ parameters.MODE }}
  displayName: '${{ parameters.OS_NAME }} ${{ parameters.BUILD_SYSTEM }}: ${{ parameters.BUILD_TYPE }}, ${{ parameters.MODE }}'

  timeoutInMinutes: 0

  pool:
      vmImage: windows-2019

  variables:
    ${{ insert }}: ${{ parameters }}

  steps:
  - pwsh: .ci\windows\dump-vm-specs.ps1
    displayName: Dump VM specs

  - script: set
    displayName: Dump environment variables

  - task: BatchScript@1
    displayName: Setup dependencies
    inputs:
      filename: .ci\windows\setup-dependencies.bat
      modifyEnvironment: true

  - script: call .ci\windows\install-wrf.bat
    displayName: Install WRF

  - ${{ if eq(parameters.WATS_RUN, 'true') }}:
    - template: wats_run.yml

  - ${{ if eq(parameters.RELEASE, 'true') }}:
    - template: release.yml
      parameters:
        ${{ insert }}: ${{ parameters }}